<?php
/**
 * Copyright © 2013-2017 Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile
?>
<?php
/** @var $block \Magento\Framework\View\Element\Template */
/** @var $helper \Magento\Search\Helper\Data */
$helper = $this->helper('Magento\Search\Helper\Data');
?>
<div class="block block-search">
    <div class="block block-title"><strong><?php /* @escapeNotVerified */ echo __('Search'); ?></strong></div>
    <div class="block block-content">
        <form class="form minisearch" id="search_mini_form" action="<?php /* @escapeNotVerified */ echo $helper->getResultUrl() ?>" method="get">

            <div class="field search">
                <label class="label" for="search" data-role="minisearch-label">
                    <span><?php /* @escapeNotVerified */ echo __('Search'); ?></span>
                </label>
                <div class="control">


                    <?php /* IDS - Select category to search */ ?>
                    <?php
                    $objectManager = \Magento\Framework\App\ObjectManager::getInstance();
                    $registry = $objectManager->get('Magento\Framework\Registry');
                    /** @var \Magento\Store\Model\StoreManager $storeManager */
                    $storeManager = $objectManager->create('Magento\Store\Model\StoreManager');

                    $currentCategory = $registry->registry('current_category');

                    $category = $objectManager->create(\Magento\Catalog\Model\Category::class); /* @var $category \Magento\Catalog\Model\Category */
                    if (is_object($currentCategory)) {
                        $currentCategoryPath = $currentCategory->getPathIds();
                    } else {
                        $currentCategoryPath = array();
                    }
                    $category->load($storeManager->getStore()->getRootCategoryId());
                    $childrenString = $category->getChildren();
                    $children = explode(',', $childrenString);
                    $categoryOptions = '';
                    foreach ($children as $c) {
                        $categoryName = $category->load($c)->getName();

                        if ($this->getRequest()->getParam('cat') == "") {
                            $selected = (in_array($c, $currentCategoryPath)) ? 'SELECTED' : '';
                        } else {
                            $selected = ($this->getRequest()->getParam('cat') == $c) ? 'SELECTED' : '';
                        }
                        $categoryOptions .= '<option title="' . $categoryName . '" value="' . $c . '" ' . $selected . '>' . $categoryName . '</option>' . "\n";
                    }
                    ?>

                    <div class="search-in-selector">
                        <select name="cat" class="search-in-cat" <?php /* onchange="this.form.submit()"*/ ?> >
                            <option value=""><?php echo __('All'); ?></option>
                            <?php echo $categoryOptions ?>
                        </select>

                        <select class="search-in-cat-tmp-select-width">
                            <option class="tmp-select-option"></option>
                        </select>

                    </div>
                    <?php /* END IDS - Select category to search */ ?>


                    <input id="search"
                           data-mage-init='{"quickSearch":{
                                "formSelector":"#search_mini_form",
                                "url":"<?php /* @escapeNotVerified */ echo $block->getUrl('search/ajax/suggest', ['_secure' => $block->getRequest()->isSecure()]); ?>",
                                "destinationSelector":"#search_autocomplete"}
                           }'
                           type="text"
                           name="<?php /* @escapeNotVerified */ echo $helper->getQueryParamName() ?>"
                           value="<?php /* @escapeNotVerified */ echo $helper->getEscapedQueryText() ?>"
                           placeholder="<?php /* @escapeNotVerified */ echo __('Search entire store here...'); ?>"
                           class="input-text"
                           maxlength="<?php /* @escapeNotVerified */ echo $helper->getMaxQueryLength();?>"
                           role="combobox"
                           aria-haspopup="false"
                           aria-autocomplete="both"
                           autocomplete="off"/>
                    <div id="search_autocomplete" class="search-autocomplete"></div>
                    <?php echo $block->getChildHtml() ?>
                </div>
            </div>
            <div class="actions">
                <button type="submit"
                        title="<?php echo $block->escapeHtml(__('Search')) ?>"
                        class="action search">
                    <span><?php /* @escapeNotVerified */ echo __('Search'); ?></span>
                </button>
            </div>
        </form>
    </div>
</div>
