<?php
/**
 * Copyright © 2013-2017 Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

/** @var $block \Magento\Catalog\Block\Product\View */
?>
<?php $_product = $block->getProduct(); ?>

<?php
/* IDS */
$objectManager = \Magento\Framework\App\ObjectManager::getInstance();
$helper = $objectManager->get(\Ids\Configurabletabletier\Helper\Data::class); /* @var $helper \Ids\Configurabletabletier\Helper\Data */
$attributeSets = $helper->geAttributeSetsFromConfig();
$productAttributeSetId = $_product->getAttributeSetId();
/* END IDS */
?>

<?php $buttonTitle = __('Update Cart'); ?>
<?php if ($_product->isSaleable()): ?>
    <div class="box-tocart update">
        <fieldset class="fieldset">



            <?php /* IDS */ ?>
            <?php
            /* @var $currencysymbol \Magento\Directory\Model\Currency */
            $currencysymbol = $objectManager->get(\Magento\Directory\Model\Currency::class);
            ?>

            <div class="price-box">
                <span><?php echo __('Subtotal'); ?>:&nbsp;</span>
                <span id="subtotalprice"><?php echo $currencysymbol->format('0.00', array(), false); ?></span>
            </div>

            <div class="actions">
                <button type="submit"
                        title="<?php /* @escapeNotVerified */ echo $buttonTitle ?>"
                        class="action primary tocart"
                        id="product-updatecart-button">
                    <span><?php /* @escapeNotVerified */ echo $buttonTitle ?></span>
                </button>
                <?php echo $block->getChildHtml('', true) ?>
            </div>

            <?php if($helper->isModuleActive() && in_array($productAttributeSetId, $attributeSets)) { ?>

                <?php
            } else {
                ?>
                <?php if ($block->shouldRenderQuantity()): ?>
                    <div class="field qty">
                        <label class="label" for="qty"><span><?php /* @escapeNotVerified */ echo __('Qty') ?></span></label>
                        <div class="control">
                            <input type="number" name="qty" id="qty" maxlength="12" value="<?php /* @escapeNotVerified */ echo $block->getProductDefaultQty() * 1 ?>" title="<?php /* @escapeNotVerified */ echo __('Qty') ?>" class="input-text qty" data-validate="{'required-number':true,digits:true}"/>
                        </div>
                    </div>
                <?php endif; ?>
                <?php
            } ?>
            <?php /* END IDS */ ?>

        </fieldset>
    </div>
    <script type="text/x-magento-init">
        {
            "#product_addtocart_form": {
                "validation": {},
                "addToCart": {
                    "cartButtonId": "#product-updatecart-button",
                    "cartForm": "#product_addtocart_form"
                }
            }
        }
    </script>
<?php endif; ?>

<?php /* IDS - Include js for calculate subtotal */ ?>
<?php
echo $this->getLayout()->createBlock("Magento\Framework\View\Element\Template")->setTemplate("Ids_Configurabletabletier::product/view/addtocart_js.phtml")->toHtml();
?>
<?php /* END IDS - Include js for calculate subtotal */ ?>