<div class="footer_box_cont">
    <div class="footer_box">
        <h1>Shop Online <br />
            and Save</h1>
        <div class="product_cont"><img src="<?php echo $this->getViewFileUrl('images/gown.png');?>" /></div>
        <div class="product_cont2"> <strong>Shiny Red Gown</strong>
            <p>In stock ready to ship</p>
            <a href="<?php echo $this->getUrl('shop-now')?>" class="more_btn">Shop Now</a> </div>
    </div>
    <div class="footer_box">
        <h1>Contact Information</h1>
        <div class="company_info">
            <div class="info12"><img src="<?php echo $this->getViewFileUrl('images/tollfree.png');?>" /><span><strong>Toll Free:</strong> 1-866-303-3822</span></div>
            <div class="info12"><img src="<?php echo $this->getViewFileUrl('images/call.png');?>" /><span><strong>Direct:</strong> 1-973-396-8190</span></div>
            <div class="info12"><img src="<?php echo $this->getViewFileUrl('images/phone.png');?>" /><span><strong>Fax:</strong> 1-973-808-9196</span></div>
            <div class="info12"><img src="<?php echo $this->getViewFileUrl('images/email.png');?>" /><span><strong>EMail:</strong> GraduationOutlet@gmail.com</span></div>
        </div>
    </div>
    <div class="footer_box">
        <h1>Request a Quote</h1>
        <div class="para_quote"> For further Inquiry please fill the custom
            quote form
            <div class="btn_pos"><a href="<?php echo $this->getUrl('get-quote')?>" class="more_btn">Get Quote</a> </div>
        </div>
    </div>
</div>