<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

/** @var \Magento\Review\Block\Product\Review $block */
?>

<?php /* IDS - Changed child position */ ?>
<?= $block->getChildHtml() ?>
<?php /* END IDS - Changed child position */ ?>

<div id="product-review-container" data-role="product-review"></div>

<script type="text/x-magento-init">
    {
        "*": {
            "Magento_Review/js/process-reviews": {
                "productReviewUrl": "<?= $block->escapeJs($block->escapeUrl($block->getProductReviewUrl())) ?>",
                "reviewsTabSelector": "#tab-label-reviews"
            }
        }
    }
</script>
